openapi: 3.0.1
info:
  title: Identity.DirectorySettings
  version: v1.0-StagingBeta
servers:
  - url: https://graph.microsoft.com/StagingBeta/
    description: Core
paths:
  '/groups/{group-id}/settings':
    get:
      tags:
        - groups.directorySetting
      summary: Get settings from groups
      operationId: groups_ListSettings
      parameters:
        - name: group-id
          in: path
          description: 'key: group-id of group'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: group
        - $ref: '#/components/parameters/top'
        - $ref: '#/components/parameters/skip'
        - $ref: '#/components/parameters/search'
        - $ref: '#/components/parameters/filter'
        - $ref: '#/components/parameters/count'
        - name: $orderby
          in: query
          description: Order items by property values
          style: simple
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - id desc
                - displayName
                - displayName desc
                - templateId
                - templateId desc
                - values
                - values desc
              type: string
        - name: $select
          in: query
          description: Select properties to be returned
          style: simple
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - displayName
                - templateId
                - values
              type: string
        - name: $expand
          in: query
          description: Expand related entities
          style: simple
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - '*'
              type: string
      responses:
        '200':
          description: Retrieved navigation property
          content:
            application/json:
              schema:
                title: Collection of directorySetting
                type: object
                properties:
                  value:
                    type: array
                    items:
                      $ref: '#/components/schemas/microsoft.graph.directorySetting'
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
    post:
      tags:
        - groups.directorySetting
      summary: Create new navigation property to settings for groups
      operationId: groups_CreateSettings
      parameters:
        - name: group-id
          in: path
          description: 'key: group-id of group'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: group
      requestBody:
        description: New navigation property
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/microsoft.graph.directorySetting'
        required: true
      responses:
        '201':
          description: Created navigation property.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/microsoft.graph.directorySetting'
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
  '/groups/{group-id}/settings/{directorySetting-id}':
    get:
      tags:
        - groups.directorySetting
      summary: Get settings from groups
      operationId: groups_GetSettings
      parameters:
        - name: group-id
          in: path
          description: 'key: group-id of group'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: group
        - name: directorySetting-id
          in: path
          description: 'key: directorySetting-id of directorySetting'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: directorySetting
        - name: $select
          in: query
          description: Select properties to be returned
          style: simple
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - displayName
                - templateId
                - values
              type: string
        - name: $expand
          in: query
          description: Expand related entities
          style: simple
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - '*'
              type: string
      responses:
        '200':
          description: Retrieved navigation property
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/microsoft.graph.directorySetting'
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
    patch:
      tags:
        - groups.directorySetting
      summary: Update the navigation property settings in groups
      operationId: groups_UpdateSettings
      parameters:
        - name: group-id
          in: path
          description: 'key: group-id of group'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: group
        - name: directorySetting-id
          in: path
          description: 'key: directorySetting-id of directorySetting'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: directorySetting
      requestBody:
        description: New navigation property values
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/microsoft.graph.directorySetting'
        required: true
      responses:
        '204':
          description: Success
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
  /settings:
    get:
      tags:
        - settings.directorySetting
      summary: Get entities from settings
      operationId: settings.directorySetting_ListDirectorySetting
      parameters:
        - $ref: '#/components/parameters/top'
        - $ref: '#/components/parameters/skip'
        - $ref: '#/components/parameters/search'
        - $ref: '#/components/parameters/filter'
        - $ref: '#/components/parameters/count'
        - name: $orderby
          in: query
          description: Order items by property values
          style: simple
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - id desc
                - displayName
                - displayName desc
                - templateId
                - templateId desc
                - values
                - values desc
              type: string
        - name: $select
          in: query
          description: Select properties to be returned
          style: simple
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - displayName
                - templateId
                - values
              type: string
        - name: $expand
          in: query
          description: Expand related entities
          style: simple
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - '*'
              type: string
      responses:
        '200':
          description: Retrieved entities
          content:
            application/json:
              schema:
                title: Collection of directorySetting
                type: object
                properties:
                  value:
                    type: array
                    items:
                      $ref: '#/components/schemas/microsoft.graph.directorySetting'
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
    post:
      tags:
        - settings.directorySetting
      summary: Add new entity to settings
      operationId: settings.directorySetting_CreateDirectorySetting
      requestBody:
        description: New entity
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/microsoft.graph.directorySetting'
        required: true
      responses:
        '201':
          description: Created entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/microsoft.graph.directorySetting'
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
  '/settings/{directorySetting-id}':
    get:
      tags:
        - settings.directorySetting
      summary: Get entity from settings by key
      operationId: settings.directorySetting_GetDirectorySetting
      parameters:
        - name: directorySetting-id
          in: path
          description: 'key: directorySetting-id of directorySetting'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: directorySetting
        - name: $select
          in: query
          description: Select properties to be returned
          style: simple
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - displayName
                - templateId
                - values
              type: string
        - name: $expand
          in: query
          description: Expand related entities
          style: simple
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - '*'
              type: string
      responses:
        '200':
          description: Retrieved entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/microsoft.graph.directorySetting'
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
    patch:
      tags:
        - settings.directorySetting
      summary: Update entity in settings
      operationId: settings.directorySetting_UpdateDirectorySetting
      parameters:
        - name: directorySetting-id
          in: path
          description: 'key: directorySetting-id of directorySetting'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: directorySetting
      requestBody:
        description: New property values
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/microsoft.graph.directorySetting'
        required: true
      responses:
        '204':
          description: Success
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
    delete:
      tags:
        - settings.directorySetting
      summary: Delete entity from settings
      operationId: settings.directorySetting_DeleteDirectorySetting
      parameters:
        - name: directorySetting-id
          in: path
          description: 'key: directorySetting-id of directorySetting'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: directorySetting
        - name: If-Match
          in: header
          description: ETag
          schema:
            type: string
      responses:
        '204':
          description: Success
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
components:
  schemas:
    microsoft.graph.directorySetting:
      allOf:
        - $ref: '#/components/schemas/microsoft.graph.entity'
        - title: directorySetting
          type: object
          properties:
            displayName:
              type: string
              nullable: true
            templateId:
              type: string
              nullable: true
            values:
              type: array
              items:
                $ref: '#/components/schemas/microsoft.graph.settingValue'
      example:
        id: string (identifier)
        displayName: string
        templateId: string
        values:
          - '@odata.type': microsoft.graph.settingValue
    microsoft.graph.entity:
      title: entity
      type: object
      properties:
        id:
          type: string
      example:
        id: string (identifier)
    microsoft.graph.settingValue:
      title: settingValue
      type: object
      properties:
        name:
          type: string
          nullable: true
        value:
          type: string
          nullable: true
      example:
        name: string
        value: string
    odata.error:
      required:
        - error
      type: object
      properties:
        error:
          $ref: '#/components/schemas/odata.error.main'
    odata.error.main:
      required:
        - code
        - message
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        target:
          type: string
        details:
          type: array
          items:
            $ref: '#/components/schemas/odata.error.detail'
        innererror:
          type: object
          description: The structure of this object is service-specific
    odata.error.detail:
      required:
        - code
        - message
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        target:
          type: string
  responses:
    error:
      description: error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/odata.error'
  parameters:
    top:
      name: $top
      in: query
      description: Show only the first n items
      schema:
        minimum: 0
        type: integer
      example: 50
    skip:
      name: $skip
      in: query
      description: Skip the first n items
      schema:
        minimum: 0
        type: integer
    search:
      name: $search
      in: query
      description: Search items by search phrases
      schema:
        type: string
    filter:
      name: $filter
      in: query
      description: Filter items by property values
      schema:
        type: string
    count:
      name: $count
      in: query
      description: Include count of items
      schema:
        type: boolean
  securitySchemes:
    azureaadv2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
          tokenUrl: https://login.microsoftonline.com/common/oauth2/v2.0/token
          scopes: { }
security:
  - azureaadv2: [ ]