# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Generates a release build artifact (nuget) from HEAD of master for beta Graph workload modules.
name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - src/Beta/*
    - config/ModulesMapping.jsonc
pr: none
variables:
  MODULE_PREFIX: 'Microsoft.Graph'
  WORKLOAD_MODULE_PATH: 'src\beta\'
  GRAPH_VERSION: 'beta'
  AUTH_MODULE_PATH: 'src\Authentication\Authentication\bin\'
  AUTH_MODULE_DLL_PATTERN: 'Microsoft.Graph.Authentication.dll'

jobs:
- job: MSGraphPSSDKGeneration
  displayName: MS Graph PS SDK Beta Generation
  timeoutInMinutes: 300
  pool:
    name: Microsoft Graph
    demands: 'Agent.Name -equals Local-Agent'
  steps:
  - task: securedevelopmentteam.vss-secure-development-tools.build-task-credscan.CredScan@2
    displayName: 'Run CredScan'
    inputs:
     debugMode: false

  - task: Npm@1
    displayName: 'Install AutoRest'
    inputs:
      command: 'custom'
      customCommand: 'install -g @autorest/autorest'
  
  - task: PowerShell@2
    displayName: 'Build Auth Modules'
    inputs:
      filePath: '$(System.DefaultWorkingDirectory)/tools/GenerateAuthenticationModule.ps1'
      arguments: '-RepositoryApiKey $(Api_Key) -ArtifactsLocation $(Build.ArtifactStagingDirectory) -Build -EnableSigning'
      pwsh: true
  
  - task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
    displayName: 'ESRP DLL Strong Name (Graph Auth Module)'
    inputs:
      ConnectedServiceName: 'microsoftgraph ESRP CodeSign DLL and NuGet'
      FolderPath: $(AUTH_MODULE_PATH)
      Pattern: '$(AUTH_MODULE_DLL_PATTERN)'
      signConfigType: inlineSignParams
      inlineOperation: |
       [
           {
               "keyCode": "CP-233863-SN",
               "operationSetCode": "StrongNameSign",
               "parameters": [],
               "toolName": "sign",
               "toolVersion": "1.0"
           },
           {
               "keyCode": "CP-233863-SN",
               "operationSetCode": "StrongNameVerify",
               "parameters": [],
               "toolName": "sign",
               "toolVersion": "1.0"
           }
       ]
      SessionTimeout: 20
  
  - task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
    displayName: 'ESRP DLL CodeSigning (Graph Auth Module)'
    inputs:
      ConnectedServiceName: 'microsoftgraph ESRP CodeSign DLL and NuGet'
      FolderPath: $(AUTH_MODULE_PATH)
      Pattern: $(AUTH_MODULE_DLL_PATTERN)
      signConfigType: inlineSignParams
      inlineOperation: |
       [
           {
               "keyCode": "CP-230012",
               "operationSetCode": "SigntoolSign",
               "parameters": [
                   {
                       "parameterName": "OpusName",
                       "parameterValue": "Microsoft"
                   },
                   {
                       "parameterName": "OpusInfo",
                       "parameterValue": "http://www.microsoft.com"
                   },
                   {
                       "parameterName": "FileDigest",
                       "parameterValue": "/fd \"SHA256\""
                   },
                   {
                       "parameterName": "PageHash",
                       "parameterValue": "/NPH"
                   },
                   {
                       "parameterName": "TimeStamp",
                       "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
                   }
               ],
               "toolName": "sign",
               "toolVersion": "1.0"
           },
           {
               "keyCode": "CP-230012",
               "operationSetCode": "SigntoolVerify",
               "parameters": [],
               "toolName": "sign",
               "toolVersion": "1.0"
           }
       ]
      SessionTimeout: 20
  
  - task: PowerShell@2
    displayName: 'Generate and Build Graph Resource Modules'
    inputs:
      filePath: '$(System.DefaultWorkingDirectory)/tools/GenerateModules.ps1'
      arguments: '-RepositoryApiKey $(Api_Key) -ArtifactsLocation $(Build.ArtifactStagingDirectory)\$(GRAPH_VERSION)\ -UseLocalDoc -BetaGraphVersion -Build -EnableSigning'
      pwsh: true
  
  - task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
    displayName: 'ESRP DLL Strong Name (Graph Resource Modules)'
    inputs:
      ConnectedServiceName: 'microsoftgraph ESRP CodeSign DLL and NuGet'
      FolderPath: $(WORKLOAD_MODULE_PATH)
      Pattern: '$(MODULE_PREFIX).*.private.dll'
      signConfigType: inlineSignParams
      inlineOperation: |
       [
           {
               "keyCode": "CP-233863-SN",
               "operationSetCode": "StrongNameSign",
               "parameters": [],
               "toolName": "sign",
               "toolVersion": "1.0"
           },
           {
               "keyCode": "CP-233863-SN",
               "operationSetCode": "StrongNameVerify",
               "parameters": [],
               "toolName": "sign",
               "toolVersion": "1.0"
           }
       ]
      SessionTimeout: 20
  
  - task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
    displayName: 'ESRP DLL CodeSigning (Graph Resource Module)'
    inputs:
      ConnectedServiceName: 'microsoftgraph ESRP CodeSign DLL and NuGet'
      FolderPath: $(WORKLOAD_MODULE_PATH)
      Pattern: '$(MODULE_PREFIX).*.private.dll, $(MODULE_PREFIX).*.psm1, $(MODULE_PREFIX).*.format.ps1xml, *.ps1'
      signConfigType: inlineSignParams
      inlineOperation: |
       [
           {
               "keyCode": "CP-230012",
               "operationSetCode": "SigntoolSign",
               "parameters": [
                   {
                       "parameterName": "OpusName",
                       "parameterValue": "Microsoft"
                   },
                   {
                       "parameterName": "OpusInfo",
                       "parameterValue": "http://www.microsoft.com"
                   },
                   {
                       "parameterName": "FileDigest",
                       "parameterValue": "/fd \"SHA256\""
                   },
                   {
                       "parameterName": "PageHash",
                       "parameterValue": "/NPH"
                   },
                   {
                       "parameterName": "TimeStamp",
                       "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
                   }
               ],
               "toolName": "sign",
               "toolVersion": "1.0"
           },
           {
               "keyCode": "CP-230012",
               "operationSetCode": "SigntoolVerify",
               "parameters": [],
               "toolName": "sign",
               "toolVersion": "1.0"
           }
       ]
      SessionTimeout: 100
  
  - task: PowerShell@2
    displayName: 'Pack Modules'
    inputs:
      targetType: 'inline'
      script: |
        $ModuleMappingConfigPath = "$(System.DefaultWorkingDirectory)/config/ModulesMapping.jsonc"
        [HashTable] $ModuleMapping = Get-Content $ModuleMappingConfigPath | ConvertFrom-Json -AsHashTable
        $ModuleMapping.Keys | ForEach-Object {
            $ModuleName = $_
            $ModuleProjectDir = "$(System.DefaultWorkingDirectory)/src/$(GRAPH_VERSION)/$ModuleName/$ModuleName"
            & $(System.DefaultWorkingDirectory)/tools/PackModule.ps1 -Module $ModuleName -GraphVersion $(GRAPH_VERSION) -ArtifactsLocation $(Build.ArtifactStagingDirectory)\$(GRAPH_VERSION)\
        }
      pwsh: true
  
  - task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
    displayName: 'ESRP NuGet CodeSigning'
    inputs:
      ConnectedServiceName: 'microsoftgraph ESRP CodeSign DLL and NuGet'
      FolderPath: '$(Build.ArtifactStagingDirectory)\$(GRAPH_VERSION)\'
      Pattern: '*.nupkg'
      signConfigType: inlineSignParams
      inlineOperation: |
            [
                {
                    "keyCode": "CP-401405",
                    "operationSetCode": "NuGetSign",
                    "parameters": [ ],
                    "toolName": "sign",
                    "toolVersion": "1.0"
                },
                {
                    "keyCode": "CP-401405",
                    "operationSetCode": "NuGetVerify",
                    "parameters": [ ],
                    "toolName": "sign",
                    "toolVersion": "1.0"
                }
            ]
      SessionTimeout: 20
  
  - task: PublishBuildArtifacts@1
    displayName: Publish Artifact Beta Modules
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(GRAPH_VERSION)'
      ArtifactName: 'drop'
      publishLocation: 'Container'

  - task: YodLabs.O365PostMessage.O365PostMessageBuild.O365PostMessageBuild@0
    displayName: 'Graph Client Tooling pipeline fail notification'
    inputs:
      addressType: serviceEndpoint
      serviceEndpointName: 'microsoftgraph pipeline status'
      title: '$(Build.DefinitionName) failure notification'
      text: 'This pipeline has failed. View the build details for further information. This is a blocking failure. '
    condition: and(failed(), ne(variables['Build.Reason'], 'Manual'))
    enabled: true