# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

parameters:
    - name: AUTH_MODULE_PATH
      displayName: 'Module Path'
      type: string
      default: 'src\Authentication\Authentication\bin\'
    - name: Api_Key
      displayName: 'Api Key'
      type: string
    - name: GRAPH_VERSION
      displayName: 'Graph Version'
      type: string
      default: 'beta'
    - name: WORKLOAD_MODULE_PATH
      displayName: 'Workload Module Path'
      type: string
      default: 'src\'
    - name: MODULE_PREFIX
      displayName: 'Module Prefix'
      type: string
      default: 'Microsoft.Graph'
    - name: EnableSigning
      displayName: 'Enable Signing'
      type: boolean
      default: false
    - name: BUILDNUMBER
      displayName: 'Build Number'
      type: string
      default: $[format('{0:yyMMddHH}', pipeline.startTime)]

jobs:
- job: MsGraphPSSDKServiceModulesGeneration
  displayName: Microsoft Graph PowerShell SDK Service Module Generation
  timeoutInMinutes: 600

  steps:
  - template: ./install-tools-template.yml

  - task: PowerShell@2
    displayName: 'Generate Profiles'
    continueOnError: false
    enabled: false
    inputs:
      targetType: 'filePath'
      pwsh: true
      filePath: $(System.DefaultWorkingDirectory)/tools/GenerateProfiles.ps1

  - task: PowerShell@2
    displayName: 'Build Auth Modules'
    inputs:
      targetType: 'inline'
      pwsh: true
      script: |
        Write-Host $(BUILDNUMBER)
        pwsh $(System.DefaultWorkingDirectory)/tools/GenerateAuthenticationModule.ps1 -ArtifactsLocation $(Build.ArtifactStagingDirectory) -Build -EnableSigning -BuildWhenEqual -ModulePreviewNumber $(BUILDNUMBER) -RepositoryName "LocalNugetFeed"

  - task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
    displayName: 'ESRP DLL Strong Name (Graph Auth Module)'
    enabled: true
    inputs:
      ConnectedServiceName: 'microsoftgraph ESRP CodeSign DLL and NuGet (AKV)'
      FolderPath: $(AUTH_MODULE_PATH)
      Pattern: 'Microsoft.Graph.Authentication.dll, Microsoft.Graph.Authentication.Core.dll'
      signConfigType: inlineSignParams
      inlineOperation: |
       [
           {
               "keyCode": "CP-233863-SN",
               "operationSetCode": "StrongNameSign",
               "parameters": [],
               "toolName": "sign",
               "toolVersion": "1.0"
           },
           {
               "keyCode": "CP-233863-SN",
               "operationSetCode": "StrongNameVerify",
               "parameters": [],
               "toolName": "sign",
               "toolVersion": "1.0"
           }
       ]
      SessionTimeout: 20
  
  - task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
    displayName: 'ESRP DLL CodeSigning (Graph Auth Module)'
    enabled: true
    inputs:
      ConnectedServiceName: 'microsoftgraph ESRP CodeSign DLL and NuGet (AKV)'
      FolderPath: $(AUTH_MODULE_PATH)
      Pattern: 'Microsoft.Graph.Authentication.dll, Microsoft.Graph.Authentication.Core.dll'
      signConfigType: inlineSignParams
      inlineOperation: |
       [
           {
               "keyCode": "CP-230012",
               "operationSetCode": "SigntoolSign",
               "parameters": [
                   {
                       "parameterName": "OpusName",
                       "parameterValue": "Microsoft"
                   },
                   {
                       "parameterName": "OpusInfo",
                       "parameterValue": "http://www.microsoft.com"
                   },
                   {
                       "parameterName": "FileDigest",
                       "parameterValue": "/fd \"SHA256\""
                   },
                   {
                       "parameterName": "PageHash",
                       "parameterValue": "/NPH"
                   },
                   {
                       "parameterName": "TimeStamp",
                       "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
                   }
               ],
               "toolName": "sign",
               "toolVersion": "1.0"
           },
           {
               "keyCode": "CP-230012",
               "operationSetCode": "SigntoolVerify",
               "parameters": [],
               "toolName": "sign",
               "toolVersion": "1.0"
           }
       ]
      SessionTimeout: 20
  
  - task: PowerShell@2
    displayName: 'Generate and Build Graph Resource Modules'
    inputs:
      targetType: 'inline'
      pwsh: true
      script: |
         Write-Host $(BUILDNUMBER)
         pwsh $(System.DefaultWorkingDirectory)/tools/GenerateModules.ps1 -ArtifactsLocation $(Build.ArtifactStagingDirectory)\ -Build -Test -EnableSigning -ModulePreviewNumber $(BUILDNUMBER) -UpdateAutoRest -RepositoryName "LocalNugetFeed"
  
  - task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
    displayName: 'ESRP DLL Strong Name (Graph Resource Modules)'
    enabled: true
    inputs:
      ConnectedServiceName: 'microsoftgraph ESRP CodeSign DLL and NuGet (AKV)'
      FolderPath: $(WORKLOAD_MODULE_PATH)
      Pattern: '$(MODULE_PREFIX).*.private.dll'
      signConfigType: inlineSignParams
      inlineOperation: |
       [
           {
               "keyCode": "CP-233863-SN",
               "operationSetCode": "StrongNameSign",
               "parameters": [],
               "toolName": "sign",
               "toolVersion": "1.0"
           },
           {
               "keyCode": "CP-233863-SN",
               "operationSetCode": "StrongNameVerify",
               "parameters": [],
               "toolName": "sign",
               "toolVersion": "1.0"
           }
       ]
      SessionTimeout: 20
  
  - task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
    displayName: 'ESRP DLL CodeSigning (Graph Resource Module)'
    enabled: true
    inputs:
      ConnectedServiceName: 'microsoftgraph ESRP CodeSign DLL and NuGet (AKV)'
      FolderPath: $(WORKLOAD_MODULE_PATH)
      Pattern: '$(MODULE_PREFIX).*.private.dll, $(MODULE_PREFIX).*.psm1, $(MODULE_PREFIX).*.format.ps1xml, ProxyCmdletDefinitions.ps1, load-dependency.ps1'
      signConfigType: inlineSignParams
      inlineOperation: |
       [
           {
               "keyCode": "CP-230012",
               "operationSetCode": "SigntoolSign",
               "parameters": [
                   {
                       "parameterName": "OpusName",
                       "parameterValue": "Microsoft"
                   },
                   {
                       "parameterName": "OpusInfo",
                       "parameterValue": "http://www.microsoft.com"
                   },
                   {
                       "parameterName": "FileDigest",
                       "parameterValue": "/fd \"SHA256\""
                   },
                   {
                       "parameterName": "PageHash",
                       "parameterValue": "/NPH"
                   },
                   {
                       "parameterName": "TimeStamp",
                       "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
                   }
               ],
               "toolName": "sign",
               "toolVersion": "1.0"
           },
           {
               "keyCode": "CP-230012",
               "operationSetCode": "SigntoolVerify",
               "parameters": [],
               "toolName": "sign",
               "toolVersion": "1.0"
           }
       ]
      SessionTimeout: 160
  
  - task: PowerShell@2
    displayName: 'Pack Modules'
    inputs:
      targetType: 'inline'
      pwsh: true
      script: |
        $ModuleMappingConfigPath = '$(System.DefaultWorkingDirectory)/config/ModulesMapping.jsonc'
        [HashTable] $ModuleMapping = Get-Content $ModuleMappingConfigPath | ConvertFrom-Json -AsHashTable
        $ModuleMapping.Keys | ForEach-Object {
            $ModuleName = $_
            $ModuleProjectDir = "$(System.DefaultWorkingDirectory)/src/$ModuleName/$ModuleName"
            & $(System.DefaultWorkingDirectory)/tools/PackModule.ps1 -Module $ModuleName -ArtifactsLocation $(Build.ArtifactStagingDirectory)\ -ExcludeMarkdownDocsFromNugetPackage
        }

  - task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
    displayName: 'ESRP NuGet CodeSigning'
    enabled: true
    inputs:
      ConnectedServiceName: 'microsoftgraph ESRP CodeSign DLL and NuGet (AKV)'
      FolderPath: '$(Build.ArtifactStagingDirectory)\'
      Pattern: '*.nupkg'
      signConfigType: inlineSignParams
      inlineOperation: |
            [
                {
                    "keyCode": "CP-401405",
                    "operationSetCode": "NuGetSign",
                    "parameters": [ ],
                    "toolName": "sign",
                    "toolVersion": "1.0"
                },
                {
                    "keyCode": "CP-401405",
                    "operationSetCode": "NuGetVerify",
                    "parameters": [ ],
                    "toolName": "sign",
                    "toolVersion": "1.0"
                }
            ]
      SessionTimeout: 20

  - task: NuGetCommand@2
    displayName: 'NuGet Publish To Local Build Feed'
    inputs:
      command: push
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/Microsoft.Graph.*.nupkg'
      publishVstsFeed: '0985d294-5762-4bc2-a565-161ef349ca3e/edc337b9-e5ea-49dd-a2cb-e8d66668ca57'
      allowPackageConflicts: true

  - task: PublishBuildArtifacts@1
    displayName: Publish Artifact Beta Modules
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/'
      ArtifactName: 'drop'
      publishLocation: 'Container'
