# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Validate pull requests to master and dev branches for Graph workload modules.
name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
pr:
  branches:
    include:
    - master
    - dev
    - milestone/*
  paths:
    include:
    - src/Beta/*
    - config/ModulesMapping.jsonc
trigger: none

variables:
  GRAPH_VERSION: 'beta'

jobs:
- job: MSGraphPSSDKValidation
  displayName: MS Graph PS SDK Beta Validation
  timeoutInMinutes: 300
  pool:
    vmImage: 'windows-latest'
  
  steps:
  - task: securedevelopmentteam.vss-secure-development-tools.build-task-credscan.CredScan@2
    displayName: 'Run CredScan'
    inputs:
     debugMode: false
  
  - task: Npm@1
    displayName: 'Install AutoRest'
    inputs:
      command: 'custom'
      customCommand: 'install -g autorest'
  
  - task: PowerShell@2
    displayName: 'Generate and Build Graph Resource Modules'
    inputs:
      filePath: '$(System.DefaultWorkingDirectory)/tools/GenerateModules.ps1'
      arguments: '-RepositoryApiKey $(Api_Key) -Build'
      pwsh: true
  
  - task: YodLabs.O365PostMessage.O365PostMessageBuild.O365PostMessageBuild@0
    displayName: 'Graph Client Tooling pipeline fail notification'
    inputs:
      addressType: serviceEndpoint
      serviceEndpointName: 'microsoftgraph pipeline status'
      title: '$(Build.DefinitionName) failure notification'
      text: 'This pipeline has failed. View the build details for further information. This is a blocking failure. '
    condition: and(failed(), ne(variables['Build.Reason'], 'Manual'))
    enabled: true